general:
  not_player: "&cYou must be a player to use this command"
  no_permission: "&cYou do not have permission to use this command"
  keep_player_data: false # Keep player data even if they disconnect.
prefix:
  admin_prefix: "[A] "
  staff_prefix: "[S] "