name: StaffChat
version: 1.0
author: ArwenMC
authors: ["Christopher Nethercott"]
main: com.arwenmc.StaffChat
commands:
  chat:
    usage: /chat <default/admin/staff>
    description: Switch your chat channel
  achat:
    usage: /achat <message>
    description: Send a message to the admin channel
    alias: [a]
  schat:
    usage: /schat <message>
    description: Send a message to the staff channel
    alias: [s]
  staffchat:
    usage: /staffchat dumpchannels
    description: Mainly for debugging prints all the players and what channel they are in.